_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.8
            "8":
                - 5
                - 9
            "12": 0.19.8
            "13": linux-x86_64
data:
    value:
        batch_size: 256
        color_jitter_strength: 0
        crop_scale:
            - 0.3
            - 1
        crop_size: 224
        image_folder: imagenet_full_size/061417/
        num_workers: 10
        pin_mem: true
        root_path: src/datasets
        use_color_distortion: false
        use_gaussian_blur: false
        use_horizontal_flip: false
logging:
    value:
        folder: experiments/vittiny-ep.50_sina/
        write_tag: jepa
mask:
    value:
        allow_overlap: false
        aspect_ratio:
            - 0.75
            - 1.5
        enc_mask_scale:
            - 0.85
            - 1
        min_keep: 10
        num_enc_masks: 5
        num_pred_masks: 1
        patch_size: 14
        pred_mask_scale:
            - 0.15
            - 0.2
meta:
    value:
        copy_data: false
        load_checkpoint: false
        model_name: vit_tiny
        pred_depth: 12
        pred_emb_dim: 384
        read_checkpoint: null
        use_bfloat16: true
optimization:
    value:
        ema:
            - 0.996
            - 1
        epochs: 50
        final_lr: 1e-06
        final_weight_decay: 0.0004
        grad_clip_value: 1
        ipe_scale: 1
        loss: sina
        lr: 0.001
        start_lr: 0.0002
        use_lars: false
        warmup: 3
        weight_decay: 0.0004
